### ISSUE TITLE
Symbolically-linked directories mishandled

### ISSUE THREAD

**Issue by stacksmith** [hedyhli/spsrv#1]
It appears that creating a symbolic link to a directory and hitting the directory with a server return something it really shouldn't:
```
ln -s . crap

hit it with a browser:

ELF>@X<@8@@@@hh
```
Accessing files _inside_ the symbolic directory works fine.

So the anomaly seems to be in the code that tries to index the directory itself.

**Comment by hedyhli** [comment]
Hi, I wasn't able to reproduce this. Can you show the full structure of the directory (or the URL of your server) which you're having this issue?

By the way,

> `ln -s . crap`

It seems like doing this would create recursion, where the parent folder contains a symbolic link `crap`, which references the parent folder, which again contains the same symbolic link `crap`... I'm curious what your use-case is that needed this?

In any case, I did `ln -s . crap` on a folder that did not contain a `index.gmi`, and spsrv was able to serve the directory listing of the folder; perhaps you're using an older version or it's an issue with the client?

**Comment by stacksmith** [comment]
## Here is an example:
The links are live, so please try it.
OK, say `session-id6AFA` is a symbolic link to the `public_spartan` directory, visible to the outside as `spartan://tilde.cafe/~spellbinding/`, which contains a cgi script `env.cgi`:
```
spartan://tilde.cafe/~spellbinding/s/session-id6AFA/env.cgi
which is the same as
spartan://tilde.cafe/~spellbinding/env.cgi
```
works as intended, while
```
spartan://tilde.cafe/~spellbinding/s/session-id6AFA/
```
results in garbage, `ELF` in my case.

Note: the 'ELF' in the string worries me, as obviously some kind of an executable is being accessed erroneously.
## Use case:
It is pretty much impossible to portably keep a session id for a Spartan application, as browsers such as Lagrange do not pass query-string from =: urls back to the server, and Spartan servers (such as SPSRV) do not support arbitrary paths containing CGI scripts in the middle (see discussion in https://github.com/skyjake/lagrange/issues/491, where @michael-lazar states that servers should support urls such as `spartan://foo/cgi/bar/baz` with the cgi script sandwiched in the middle!  BTW, I would not resort to such insanity if I was writing a server)

In order to create Spartan session-based applications, the only remaining venue is to pass the session information in the path of the URI itself, to the left of the cgi.  My CGI creates a symbolic link with the same name as the session name, pointing back at the cgi directory.  This incorporates the session-id into the URI path, aliasing the cgi directory.  Further accesses via the link provide the CGI with the session-id; at the end of the session the CGI deletes the link.

There is no problem with the circularity of the link.

As this is the only remaining way to keep state, please do not remove this capability.  I already screwed myself by reporting a bug to skyjake and had to come up with this, the only remaining, scheme.  Please, make sure symbolic links are processed as they are now.

**Comment by stacksmith** [comment]
opening another issue...

It is not what I thought - links have nothing to do with it.  It is that calling a cgi script `index.gmi` breaks SPSRV.  I opened a separate issue, and I think we are OK with links.

**Comment by hedyhli** [comment]
> It is pretty much impossible to portably keep a session id for a Spartan application, as browsers such as Lagrange do not pass query-string from =: urls back to the server, and Spartan servers (such as SPSRV) do not support arbitrary paths containing CGI scripts in the middle (see discussion in [skyjake/lagrange#491](https://github.com/skyjake/lagrange/issues/491), where @michael-lazar states that servers should support urls such as `spartan://foo/cgi/bar/baz` with the cgi script sandwiched in the middle! BTW, I would not resort to such insanity if I was writing a server)

This is on my todo list and will definitely be implemented in the future (and like mozz mentioned, molly-brown does support this so it wouldn't be a hard task).

> In order to create Spartan session-based applications, the only remaining venue is to pass the session information in the path of the URI itself, to the left of the cgi. My CGI creates a symbolic link with the same name as the session name, pointing back at the cgi directory. This incorporates the session-id into the URI path, aliasing the cgi directory. Further accesses via the link provide the CGI with the session-id; at the end of the session the CGI deletes the link.

This sounds like an interesting way to have spartan applications that have sessions and states, but you may find passing information through the extra path after the CGI script easier.

> As this is the only remaining way to keep state, please do not remove this capability. I already screwed myself by reporting a bug to skyjake and had to come up with this, the only remaining, scheme. Please, make sure symbolic links are processed as they are now.

Of course! I really like what you are building, even more so in that it is being done using a static file server with CGI (instead of, say an actual server that handles the protocol and the requests itself).
