### ISSUE TITLE
Unable to execute /~user/index.gmi CGI

### ISSUE THREAD

**Issue by stacksmith** [hedyhli/spsrv#2]
Try hitting this URL:
```
spartan://tilde.cafe/~spellbinding/
```
It contains a cgi executable called `index.gmi`.  Instead of running it as a CGI script, SPSRV returns it as a file, the actual elf executable!

This seems to be a consequence of how the default processing of hitting a directory URI is handled in SPSRV.

**Comment by hedyhli** [comment]
This seems to only happen with /index.gmi CGI scripts for user directories. Thanks for raising the issue, I'll fix this as soon as I can.

**Comment by hedyhli** [comment]
The build version on tilde.cafe has been updated and your script should run now (the CGI error might be a problem with your script itself), let me know if you've run into any other issues.
